# 应用名称
spring:
  application:
  name: secondkilling
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: second_killing
    # 数据库连接地址
    url: jdbc:mysql://175.178.185.62:3306/second_killing?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    # 数据库用户名&密码：
    username: root
    password: 333333
  redis:
    host: 127.0.0.1
    port: 6379
#    password: second-kill

#应用服务 WEB 访问端口
server:
  port: 8888


# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认名称是类名）
  type-aliases-package: com.example.secondkill.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

## 消费者的组名
#apache:
#  rocketmq:
#    consumer:
#    PushConsumer: orderConsumer
#    # 生产者的组名
#    producer:
#      producerGroup: Producer
#    # NameServer地址
#    namesrvAddr: 127.0.0.1:9876



